In [1]:
import re
import pandas as pd

In [2]:
f = open('WhatsApp Chat with SBJ-6-Sem-CSE(AI&ML)23-27.txt', 'r', encoding='utf-8')

In [3]:
data = f.read()

In [5]:
print(data)

8/26/23, 12:20 - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. *Learn more*.
8/26/23, 11:32 - Arpit Gupta Tg created group "First year AIML 23-24 Sec F"
8/26/23, 12:20 - You joined using this group's invite link
8/26/23, 12:24 - +91 97663 24881 joined using a group link.
8/26/23, 12:25 - Tanvi joined using a group link.
8/26/23, 12:26 - Divyani wath joined using a group link.
8/26/23, 12:27 - +91 93717 17980 joined using a group link.
8/26/23, 12:33 - Tejas joined using a group link.
8/26/23, 12:36 - +91 93092 07605 joined using a group link.
8/26/23, 12:51 - +91 98905 65707 joined using a group link.
8/26/23, 13:03 - Shourya joined using a group link.
8/26/23, 13:05 - +91 98819 60844 joined using a group link.
8/26/23, 13:07 - +91 91754 06926 joined using a group link.
8/26/23, 13:24 - Ashutosh joined using a group link.
8/26/23, 13:26 - +91 73979 00911 joined using a group link.
8/26/23, 13:40 - Utkarsh joined using a group link.
8/26/23, 14:24 - +91 87664 03464 joined using a group link.
8/26/23, 14:31 - Shivam joined using a group link.
8/26/23, 14:43 - +91 84596 01251 joined using a group link.
8/26/23, 14:56 - +91 95292 60741 joined using a group link.
8/26/23, 15:17 - +91 87670 78967 joined using a group link.
8/26/23, 15:46 - Soham joined using a group link.
8/26/23, 16:27 - Jassi joined using a group link.
8/26/23, 16:29 - Arpit Gupta Tg: <Media omitted>
8/26/23, 16:38 - +91 77769 59594 joined using a group link.
8/26/23, 17:48 - Sudanshu joined using a group link.
8/26/23, 18:45 - Arpit Gupta Tg: <Media omitted>
8/26/23, 18:45 - Arpit Gupta Tg: <Media omitted>
8/26/23, 19:07 - +91 87882 77975 joined using a group link.
8/26/23, 20:05 - +91 72639 38242 joined using a group link.
8/26/23, 21:03 - +91 74983 25268 joined using a group link.
8/26/23, 23:36 - +91 86055 89053 joined using a group link.
8/27/23, 03:41 - +91 93735 72061 joined using a group link.
8/27/23, 09:00 - Vedant Tiwade joined using a group link.
8/27/23, 09:00 - Dhanshri Raut joined using a group link.
8/27/23, 13:25 - Sameer joined using a group link.
8/27/23, 15:00 - Parth joined using a group link.
8/28/23, 00:21 - Himanshu joined using a group link.
8/28/23, 07:59 - +91 97663 52150 joined using a group link.
8/28/23, 08:30 - Arpit Gupta Tg: <Media omitted>
8/28/23, 08:31 - Arpit Gupta Tg: Check/Note your name, USN number and TG's name.
8/28/23, 09:16 - Aditya Mahalle joined using a group link.
8/28/23, 10:25 - Sujal joined using a group link.
8/28/23, 11:36 - Arpit Gupta Tg: https://forms.gle/Ye84dVTP6Ges5kGW6

Data Sheet of Teacher Guardian Student 2023-24 (DSTG 2023-24).

All TGs are informed to share this link to respective TG student. This data will be also used for creation of students official e mail id.
*As complete and correct data is required , the link will be active till 30th Aug, 2023* as it will required time to fill.
Thank you.

*For any queries related to the link feel free to call/meet me*.
8/28/23, 13:29 - +91 93221 48375 joined using a group link.
8/28/23, 14:13 - Jarrar joined using a group link.
8/28/23, 14:14 - +91 81808 64070 joined using a group link.
8/28/23, 18:51 - Sunil Tg Sir added ~ Kshitj Shelare
8/28/23, 20:02 - +91 90285 39549 joined using a group link.
8/28/23, 21:52 - +91 88001 72600 joined using a group link.
8/29/23, 06:30 - Arpit Gupta Tg added ~ Kshitj Shelare
8/29/23, 07:16 - +91 89759 45581: <Media omitted>
8/29/23, 07:16 - +91 89759 45581: Purchase this calculator as early as possible
8/29/23, 08:27 - +91 62662 44696 joined using a group link.
8/29/23, 11:24 - +91 99751 81905 joined using a group link.
8/29/23, 11:24 - Sarang joined using a group link.
8/29/23, 14:30 - Arpit Gupta Tg added ~ Ashish Nanotkar
8/29/23, 19:06 - Arpit Gupta Tg: *Students take note*
The college will remain closed on account of RAKSHABANDHAN tomorrow, 30th Aug '23.
8/31/23, 13:06 - +91 70209 17983 joined using a group link.
8/31/23, 14:33 - +91 90285 39549: All students will present in regular classroom for 4th lecture
8/31/23, 16:03 - +91 81490 59665 joined using a group link.
9/1/23, 15:01 - Arpit Gupta Tg: https://forms.gle/nwCbZN75awhuMaw97
9/1/23, 15:01 - Arpit Gupta Tg: NMC Bus Route Form
9/1/23, 16:09 - Sunil Tg Sir added ~ Ashish Golghate
9/1/23, 16:18 - Arpit Gupta Tg: Saturday, 2nd Sept, '23, PPS practical of Sec F is to be shifted to F-106 as there is an event in department of emerging tech Lab.
9/1/23, 19:26 - Arpit Gupta Tg: <Media omitted>
9/1/23, 19:26 - Arpit Gupta Tg: *Attention all students*
It is for your information that students who wish to participate in college level activities and/or in activities of other institution shall take prior permission from their TG and the department.
9/1/23, 19:33 - Arpit Gupta Tg: *Applications Open - Kiran Girls Scholarship and Mentoring Program 2023-24*

Now is your chance to apply to our prestigious 👧 Kiran Girls Scholarship and Mentoring Program! In the last 13 years, we have successfully supported girls in pursuing their bachelor’s degree in 👩‍💻Computer Science/Information Technology/ Data Science - AI/ ML across Pune, Nagpur, Goa, Hyderabad, and Bangalore.

You can get a scholarship of Rs.50,000 if you are a 1st year or a direct 2nd year student, admitted in 2023.

Hurry up! The last day of registration is 25 September. Apply now:  https://bit.ly/3ElNi9p

#ScholarshipForGirls #KiranGirlsScholarship
9/2/23, 08:34 - Arpit Gupta Tg: 👆🏻Reminder
9/2/23, 13:25 - Sunil Tg Sir: <Media omitted>
9/2/23, 13:26 - Sunil Tg Sir: Check your mail ID and suggest if any  corrections 👆
9/4/23, 13:33 - Sunil Tg Sir: 👆 Above students come and meet me now
9/4/23, 13:33 - Sunil Tg Sir: In chemistry lab
9/4/23, 13:33 - Sunil Tg Sir: <Media omitted>
9/4/23, 13:46 - Sunil Tg Sir: <Media omitted>
9/4/23, 13:46 - Sunil Tg Sir: 👆
9/4/23, 13:47 - Sunil Tg Sir: Why other not
9/4/23, 15:21 - Arpit Gupta Tg: Leela Poonawala Scholarship form filling schedule -

Date 05.09.23
Time 3 pm
Venue Computer lab F 006

Criteria for scholarship
70℅ in 10 th and 12 th and annual family income up to 3,50,000 rs only.

Required Documents
1. Proof of age.
2. Adhar card
3. 10th and 12th marksheet
4. Allotment letter
5. Income proof
Additional document to submit for farmer parents is 7/12 document, land passbook.
9/4/23, 15:21 - Arpit Gupta Tg: This is only for girl students.
9/4/23, 17:32 - Sunil Tg Sir: <Media omitted>
9/4/23, 17:35 - Arpit Gupta Tg: This message was deleted
9/5/23, 20:42 - Sunil Tg Sir: Leela Poonawala Scholarship form filling schedule -

Date 05.09.23
Time 3 pm
Venue Computer lab F 006

Criteria for scholarship
70℅ in 10 th and 12 th and annual family income up to 3,50,000 rs only.

Required Documents
1. Proof of age.
2. Adhar card
3. 10th and 12th marksheet
4. Allotment letter
5. Income proof
Additional document to submit for farmer parents is 7/12 document, land passbook.
9/6/23, 12:55 - Arpit Gupta Tg: <Media omitted>
9/6/23, 17:23 - +91 95457 84666: <Media omitted>
9/6/23, 20:39 - Purval joined using a group link.
9/7/23, 09:51 - +91 95457 84666: <Media omitted>
9/7/23, 09:54 - +91 95457 84666: Guest lecture @ 11.30 am at MBA seminar Hall.
9/7/23, 11:05 - +91 95457 84666: CR kindly asked the students to gather at MBA seminar hall sharp 11.30 after first class
9/7/23, 11:39 - Sunil Tg Sir: https://docs.google.com/forms/d/e/1FAIpQLSdIFy_OBDpbUFpTJZz1vCHHZWqlVA9h6IHa7LdP5xlzojvoKA/viewform?usp=sf_link
9/7/23, 11:40 - Sunil Tg Sir: 👆For email registration s
9/7/23, 11:41 - Sunil Tg Sir: Only for those who not registered previously
9/7/23, 11:41 - Sunil Tg Sir: 👆Not for all
9/7/23, 11:42 - Sunil Tg Sir: Sir, these students didn't get their Email Id
1. Burhanuddin Husain
2. Mithilesh Kose
3. Tejas Kayarkar
4. Purval Nayak
5. Shourya Choure
6. Aditya Sinha
7. Parth Wadekar
8. Khushboo Gautam
9. Sanskruti Mishra
10. Shreyash Karde
11. Sarang Ghatulkar
12. Aditya Mahalle
13. Sahil Bhoyar
14. Om Polakhare
15. Himanshu Kakde
16. Meksha Tajane
9/7/23, 11:42 - Sunil Tg Sir: 👆Only for these students
9/7/23, 14:21 - +91 95953 52489: <Media omitted>
9/7/23, 21:46 - +91 90110 18200: https://www.youtube.com/watch?v=zHt5Mdr0QFk
9/7/23, 21:49 - ~ Amit Tajne B+ive changed the group name from "First year AIML 23-24 Sec F" to "First Year AIML 23-24 Sec F"
9/9/23, 13:08 - +91 95953 52489: <Media omitted>
9/9/23, 13:12 - Arpit Gupta Tg: <Media omitted>
9/9/23, 18:27 - Arpit Gupta Tg: <Media omitted>
9/9/23, 18:28 - Arpit Gupta Tg: <Media omitted>
9/11/23, 12:56 - Sunil Tg Sir: <Media omitted>
9/11/23, 12:56 - Sunil Tg Sir: <Media omitted>
9/11/23, 15:48 - Sunil Tg Sir: <Media omitted>
9/11/23, 15:49 - Sunil Tg Sir: 👆E-mail IDs for students who were having problems to logged in earlier...
9/12/23, 12:38 - Arpit Gupta Tg: <Media omitted>
9/12/23, 15:29 - +91 90110 18200: Ref.: SBJITMR/Lib./2023-24/91

Date: 12-09-2023

Circular
	Subject: B.Tech 1st Year Students Library cum Identity card.
All the B.Tech 1st year students of the Institute are hereby instructed to fill the Library cum identity card digital form on or before 27/09/2023.

Kindly Visit   https://id4u.in/home from your Smart Mobile Phone
Then type correct Username and Password

Username	: sbji
Password	: 2308i712

After that follow the instruction and fill the relevant information carefully, Contact library department for further process.


Dr. Shruti S.Manohare
Librarian
S.B.J.I.T.M.R,Nagpur.
9/12/23, 16:06 - Arpit Gupta Tg: https://forms.gle/3SF2BeMqzqRfYxBD8

*Eco & Innovation Club 2023-24*

Objectives of Eco & Innovation club are to spread awareness about sustainable environment and to create an ecosystem for innovation.

*Applications are invited for two posts (Team leader & members) for this session*.

Selected candidates for personal interview will be communicated by mail.

*Let's join hands for sustainable environment and innovations for society*.

Thank you.

Dr. D. B. Rana
Faculty Coordinator,
*Eco & Innovation Club 2023-24*
🌳🌍🔭⚙️🖥️
9/12/23, 16:19 - +91 95953 52489: <Media omitted>
9/12/23, 17:30 - +91 98231 16812: This message was deleted
9/12/23, 17:49 - +91 98231 16812: https://forms.gle/3SF2BeMqzqRfYxBD8

*Eco & Innovation Club 2023-24*

Objectives of Eco & Innovation club are to spread awareness about sustainable environment and to create an ecosystem for innovation.

*Applications are invited for two posts (Team leader & members) for this session*.

Selected candidates for personal interview will be communicated by mail.

*Let's join hands for sustainable environment and innovations for society*.

Thank you.

Dr. D. B. Rana
Faculty Coordinator,
*Eco & Innovation Club 2023-24*
🌳🌍🔭⚙️🖥️
9/12/23, 17:50 - +91 98231 16812: https://forms.gle/YaVTdKdDvN4t3UKw8

हिन्दी दिवस उत्सव २०२३
 इच्छुक विद्यार्थी कथा और कविता इस लिंक पर सांझा करे. धन्यवाद !
🙏🙏🙏
9/12/23, 19:08 - Arpit Gupta Tg: <Media omitted>
9/13/23, 11:42 - Arpit Gupta Tg: <Media omitted>
9/13/23, 11:58 - +91 98231 16812: Login with sbjit.edu.in to submit the poem or story.
9/13/23, 16:40 - Arpit Gupta Tg: <Media omitted>
9/13/23, 20:03 - +91 98231 16812: Students who applied for various positions of Eco & Innovation club are instructed to join google meet.
Link is share on their registered email id.
Thank you.
9/14/23, 07:34 - +91 98231 16812: https://youtube.com/watch?v=m7zeLjPSQP8&si=JC4q-0IQ4_fKF0ZD

पैर...पग...पाद...चरण और कई पर्यायी शब्द है...अंग्रेजी मे एक ही शब्द है लेग (Leg) !

सहज..सुगम..सुंदर भाषा याने हिन्दी भाषा....
*हिन्दी भाषा दिवस*
की हार्दिक शुभकामनाए !
- डॉ. दिलीपकुमार राणा (मिञ)
🙏🙏🙏
9/14/23, 09:34 - +91 98231 16812: *Eco & Innovation Club 2023-24*

Ms. Aaliya from Section A is selected as student coordinator of Eco & Innovation Club for the session 2023-24.

Members from class (1 from each each) will be announced soon.

Congratulations !
🌳🌍🔭📐🖥️⚙️
9/14/23, 10:56 - +91 95457 84666: Things to be brought for craft class(Twist &Pop):

- Colour chart paper 1/2 sheet
- Designer paper 2 sheets A4( both should be of different design)
- glue/fevicol
- Ruler Scale
- Pencil
9/14/23, 10:56 - +91 95457 84666: Kindly carry things above mentioned for tomorrow class of LL2
9/14/23, 12:37 - +91 98231 16812: हिंदी दिवस की सभी को शुभकामनाए.
हिंदी दिवस उत्सव २०२३ मे इस वर्ष स्वर्गीय अटल बिहारी बाजपेयी स्वंय रचित कथा कथन तथा कविता पठन की स्पर्धा का आयोजन किया गया है.
जिन्होंने अपणी रचणाये google link पर सांझा की है वे सभी स्पर्धक रसायन शास्त्र प्रयोगशाला मे मिले (समय दोपहर १.४०).
इसी के साथ जिन्हे भी आज इस स्पर्धा मे भाग लेना वे भी आ कर मिल सकते है (on spot registration)
धन्यवाद !
9/14/23, 12:38 - Sunil Tg Sir: हिंदी दिवस की सभी को शुभकामनाए.
हिंदी दिवस उत्सव २०२३ मे इस वर्ष स्वर्गीय अटल बिहारी बाजपेयी स्वंय रचित कथा कथन तथा कविता पठन की स्पर्धा का आयोजन किया गया है.
जिन्होंने अपणी रचणाये google link पर सांझा की है वे सभी स्पर्धक रसायन शास्त्र प्रयोगशाला मे मिले (समय दोपहर १.४०).
इसी के साथ जिन्हे भी आज इस स्पर्धा मे भाग लेना वे भी आ कर मिल सकते है (on spot registration)
धन्यवाद !
9/14/23, 14:50 - Sunil Tg Sir: <Media omitted>
9/14/23, 14:50 - Sunil Tg Sir: <Media omitted>
9/14/23, 14:50 - Sunil Tg Sir: Quiz Contest Link

*https://forms.gle/kqFGCWuKLRggp7W1A*
9/14/23, 15:24 - +91 98231 16812: All students who are not the part of any activity are instructed to assemble at MBA hall for Hindi Divas 2023.
9/14/23, 15:30 - Sunil Tg Sir: Come to seminar hall @ ground floor fast....👆
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:00 - +91 95453 31118: <Media omitted>
9/14/23, 21:08 - +91 98231 16812: <Media omitted>
9/14/23, 21:08 - +91 98231 16812: <Media omitted>
9/14/23, 21:08 - +91 98231 16812: <Media omitted>
9/14/23, 21:08 - +91 98231 16812: <Media omitted>
9/14/23, 21:08 - +91 98231 16812: <Media omitted>
9/14/23, 21:08 - +91 98231 16812: <Media omitted>
9/14/23, 21:08 - +91 98231 16812: <Media omitted>
9/14/23, 21:08 - +91 98231 16812: <Media omitted>
9/17/23, 11:00 - +91 88302 79973: All the students of Section F (Batch F1) are instructed to collect the Hardware Networking journal from my desk.
9/17/23, 13:58 - Sunil Tg Sir: <Media omitted>
9/17/23, 13:59 - Sunil Tg Sir: Above Students Call or Message me Urgent...stating reason of your absentee
9/17/23, 13:59 - Sunil Tg Sir: 👆
9/18/23, 17:41 - Sunil Tg Sir: <Media omitted>
9/18/23, 17:41 - Sunil Tg Sir: Remaining students Email ID.
Check your email ID and login with email id.
9/20/23, 13:40 - +91 90110 18200: <Media omitted>
9/21/23, 06:27 - +91 95457 84666: Things to be brought for craft class(Twist &Pop):

- Colour chart paper 1/2 sheet
- Designer paper 2 sheets A4( both should be of different design)
- glue/fevicol
- Ruler Scale
- Pencil
9/21/23, 06:28 - +91 95457 84666: For today's lecture
9/21/23, 10:43 - +91 90110 18200: Students are not permitted to come in traditional dress or go for aarti without permission from the department
9/21/23, 20:05 - Arpit Gupta Tg: The college will remain closed tomorrow, 22nd Sept. '23, on account of Mahalaxmi Pujan
9/21/23, 20:33 - Sunil Tg Sir: The college will remain closed tomorrow, 22nd Sept. '23, on account of Mahalaxmi Pujan
9/23/23, 09:14 - Arpit Gupta Tg: College will remain closed today.
9/24/23, 10:15 - +91 90285 39549: Dear all

Electrical engineering class is scheduled at 10.35 an sharp.
Kindly join with google meet app
9/24/23, 10:18 - +91 90285 39549: https://meet.google.com/hbf-podx-zps
9/24/23, 10:40 - +91 90285 39549: All should join now
9/24/23, 16:57 - Arpit Gupta Tg: Students who have taken prior permission are allowed to attend tomorrow's IDEAYAAN event.
All other students shall attend classes as per schedule.
9/25/23, 10:23 - Sunil Tg Sir: <Media omitted>
9/25/23, 14:33 - Arpit Gupta Tg: *Kind attention*
Filling of RTMNU enrollment form is a part of a compulsory process to be done by each student.

All the students shall take note of the same and do the process immediately.
9/25/23, 15:06 - Arpit Gupta Tg: https://forms.gle/XckHnfgwDsANyZu58
9/25/23, 15:07 - Arpit Gupta Tg: Fill this immediately.

This data is required for exam section. You have to fill this form today itself up to 7 pm.
9/25/23, 15:30 - Sunil Tg Sir: Last day for submission of forum fees
9/25/23, 15:30 - Sunil Tg Sir: 👆
9/25/23, 20:52 - Arpit Gupta Tg: <Media omitted>
9/25/23, 20:53 - Arpit Gupta Tg: Communicative English :  TAE-1
9/26/23, 15:36 - Sunil Tg Sir: Batch F1 come for practical in chemistry lab
9/26/23, 15:41 - +91 88001 72600: Batch F2 come in Electrical lab immediately <This message was edited>
9/26/23, 16:13 - +91 88001 72600: Remaining students please report to the lab immediately <This message was edited>
9/26/23, 16:41 - Sunil Tg Sir: Roll No. 26 and 27 must come with their parents tomorrow or you will not be allowed to attend lectures and practicals
9/26/23, 16:41 - Sunil Tg Sir: 👆
9/26/23, 17:40 - +91 88001 72600: Roll no.43,44,49,50 and 54 also
9/26/23, 19:10 - Arpit Gupta Tg: Students who have not submitted the Google form related to Exams , are instructed to do it  immediately.
9/26/23, 19:10 - Arpit Gupta Tg: https://forms.gle/XckHnfgwDsANyZu58
9/27/23, 16:45 - Sunil Tg Sir: <Media omitted>
9/27/23, 16:45 - Sunil Tg Sir: NEP-Chemistry for Engineering ABL Notice : Students are required to go through the notice and read the guideline carefully. Last date for Submission of report (MS-Word-print ) 6/10/2023. Students are advised to review the soft copy of report before taking print.
9/27/23, 16:45 - Sunil Tg Sir: 👆
9/27/23, 17:39 - +91 90110 18200: <Media omitted>
9/27/23, 17:59 - Sunil Tg Sir: <Media omitted>
9/27/23, 19:14 - +91 93715 25696 joined using a group link.
10/1/23, 11:31 - +91 90285 39549: Dear all

Electrical engineering class is scheduled at 12.15  pm sharp.
Kindly join with google meet app
10/1/23, 11:32 - +91 90285 39549: https://meet.google.com/hbf-podx-zps
10/2/23, 11:35 - +91 90285 39549: No class today
10/3/23, 09:24 - Sunil Tg Sir: First lecture on section F  will be conducted by Arpit Gupta sir in my absence today..
10/3/23, 10:57 - +91 98906 16804: 2 and 3 lecture is mathematics gather In Room B203
10/3/23, 17:09 - +91 88001 72600: Students from F2 batch
Come immediately in Electrical lab
10/4/23, 13:02 - +91 98231 16812:
10/4/23, 13:16 - +91 98231 16812: <Media omitted>
10/4/23, 15:30 - +91 90110 18200: <Media omitted>
10/4/23, 17:19 - +91 95453 31118: <Media omitted>
10/5/23, 08:27 - Sunil Tg Sir: <Media omitted>
10/5/23, 08:28 - Sunil Tg Sir: Chemistry for Engineers : Unit IV Notes 👆🏻
10/5/23, 13:35 - Sunil Tg Sir: Chemistry for Engineering: today we are having lecture @ 3.30 to 5.30 PM.
10/5/23, 13:35 - Sunil Tg Sir: 👆very Important
10/5/23, 14:06 - +91 95457 84666: Submit the form in chemistry lab now
10/6/23, 19:26 - Arpit Gupta Tg: https://forms.gle/jKTRzjKQHt8dibGc7

Google Form Link to upload ABC id card
10/7/23, 16:53 - Sunil Tg Sir: CM23024	FAWAAZ IRSHAD AHMED
CM23027	ADITYA SUBHASH SINHA
CM23028	ANUSHKA SUSHILKUMAR SAVITA
CM23031	PRATHAM KASHINATH PIMPALIKAR
10/7/23, 16:53 - Sunil Tg Sir: Disciplinary Action: Above👆 mentioned students are not allowed to attend any class from Monday 9/10/2023 without having a meeting with HOD sir
10/8/23, 10:20 - +91 90285 39549: EE CLASS will start from 10.40 am
10/8/23, 10:21 - +91 90285 39549: https://meet.google.com/hbf-podx-zps
10/8/23, 10:42 - +91 90285 39549: Join fast
10/8/23, 11:02 - +91 98231 16812: <Media omitted>

In [6]:
pattern = r'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

In [7]:
messages = re.split(pattern, data)[1:]
len(messages)

5419

In [8]:
dates = re.findall(pattern, data)

In [9]:
df = pd.DataFrame({
    'user_message': messages,
    'message_date': dates
})

In [12]:
df['message_date'] = df['message_date'].str.strip()

In [13]:
df['message_date'] = df['message_date'].str.replace(' -', '', regex=False)

In [14]:
df['message_date'] = pd.to_datetime(df['message_date'], format='%m/%d/%y, %H:%M')

In [15]:
users = []
messages = []

for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s', message)
    
    if entry[1:]:  # user name exists
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['user'] = users
df['message'] = messages

df.drop(columns=['user_message'], inplace=True)
df.head()

<>:5: SyntaxWarning: invalid escape sequence '\w'
<>:5: SyntaxWarning: invalid escape sequence '\w'
C:\Users\fanaa\AppData\Local\Temp\ipykernel_28484\3440776221.py:5: SyntaxWarning: invalid escape sequence '\w'
  entry = re.split('([\w\W]+?):\s', message)

,message_date,user,message
0,2023-08-26 12:20:00,group_notification,Messages and calls are end-to-end encrypted. O...
1,2023-08-26 11:32:00,group_notification,"Arpit Gupta Tg created group ""First year AIML ..."
2,2023-08-26 12:20:00,group_notification,You joined using this group's invite link\n
3,2023-08-26 12:24:00,group_notification,+91 97663 24881 joined using a group link.\n
4,2023-08-26 12:25:00,group_notification,Tanvi joined using a group link.\n

In [17]:
df.rename(columns={'message_date': 'date'}, inplace=True)

In [18]:
df['year'] = df['date'].dt.year
df.head()

,date,user,message,year
0,2023-08-26 12:20:00,group_notification,Messages and calls are end-to-end encrypted. O...,2023
1,2023-08-26 11:32:00,group_notification,"Arpit Gupta Tg created group ""First year AIML ...",2023
2,2023-08-26 12:20:00,group_notification,You joined using this group's invite link\n,2023
3,2023-08-26 12:24:00,group_notification,+91 97663 24881 joined using a group link.\n,2023
4,2023-08-26 12:25:00,group_notification,Tanvi joined using a group link.\n,2023

In [19]:
df['month'] = df['date'].dt.month_name()
df['day'] = df['date'].dt.day
df['hour'] = df['date'].dt.hour
df['minute'] = df['date'].dt.minute

In [24]:
df.shape

(5419, 8)